version: "3.8" #docker composerのバージョンの指定
services:
  app:
    build: ./ #buildするdockerfileの位置
    container_name: node #作成するdockerコンテナの名前
    volumes:
      - ./show_ppl_pref_graph:/show_ppl_pref_graph #docker内と共有するフォルダの指定
    working_dir: /show_ppl_pref_graph #docker内に入った時の初期パスの指定
    ports:
      - 3000:3000 #コンテナにバインドするポートの指定（左:自分のPCポート、右:dookerコンテナのポート）
    tty: true #コンテナが勝手に終了しないための設定
    stdin_open: true #標準入出力とエラー出力をコンテナに結びつける設定